version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meusgastos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: meusgastos
      POSTGRES_PASSWORD: meusgastos123
      POSTGRES_DB: meusgastos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
